"""Loading, validation, and normalization for MTUQ workflow recipes."""

import copy
import inspect
import math
import os
import re
from collections.abc import Mapping
from datetime import datetime
from decimal import Decimal, InvalidOperation
from pathlib import Path

import numpy as np
import yaml
from yaml.constructor import ConstructorError

from mtuq.grid import (
    DeviatoricGridRandom,
    DeviatoricGridSemiregular,
    DoubleCoupleGridRandom,
    DoubleCoupleGridRegular,
    FullMomentTensorGridRandom,
    FullMomentTensorGridSemiregular,
)
from mtuq.misfit import WaveformMisfit

from .io import _resolve_path


WORKFLOW_VERSION = 1


_NUMERIC_LITERAL_RE = re.compile(
    r'^[+-]?(?:'
    r'(?:\d(?:_?\d)*)(?:\.(?:\d(?:_?\d)*)?)?'
    r'|(?:\.\d(?:_?\d)*)'
    r')(?:[eE][+-]?\d(?:_?\d)*)?$'
)


_EVENT_ID_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9_.-]*$')


_TOP_LEVEL_KEYS = {
    'version',
    'event',
    'origin_search',
    'data',
    'greens',
    'picks',
    'misfit',
    'measurements',
    'source',
    'wavelet',
    'objective',
    'plots',
    'output',
    # Generated by config.resolved.yaml and refreshed on every run.
    'workflow',
    'mtuq',
}


_SOURCE_FUNCTIONS = {
    ('dc', 'regular'): DoubleCoupleGridRegular,
    ('dc', 'random'): DoubleCoupleGridRandom,
    ('dev', 'regular'): DeviatoricGridSemiregular,
    ('dev', 'random'): DeviatoricGridRandom,
    ('fmt', 'regular'): FullMomentTensorGridSemiregular,
    ('fmt', 'random'): FullMomentTensorGridRandom,
}


_UNIT_TAGS = {
    'm': ['units:m', 'type:displacement'],
    'm/s': ['units:m', 'type:velocity'],
    'cm': ['units:cm', 'type:displacement'],
    'cm/s': ['units:cm', 'type:velocity'],
}


_SUPPORTED_PICK_TYPES = {
    'taup',
    'FK_metadata',
    'SAC_metadata',
    'user_supplied',
}


_SUPPORTED_WINDOW_TYPES = {'body_wave', 'surface_wave'}


_SUPPORTED_MEASUREMENT_ROLES = {
    'body',
    'surface',
    'rayleigh',
    'love',
}


_SUPPORTED_PLOTS = {
    'waveform',
    'beachball',
    'misfit',
}


_NUMERIC_OVERRIDE_KEYS = {
    'freq',
    'freq_min',
    'freq_max',
    'period',
    'period_min',
    'period_max',
    'window_length',
    'time_shift_min',
    'time_shift_max',
    'scaling_power',
    'scaling_coefficient',
}


class WorkflowConfigError(ValueError):
    """ Raised when a workflow recipe is malformed or unsupported
    """


class _UniqueKeyLoader(yaml.SafeLoader):
    """ Safe YAML loader that rejects duplicate mapping keys
    """


def _construct_unique_mapping(loader, node, deep=False):
    """Constructs a mapping while ensuring all keys are unique.
    YAML reader is otherwise too permissive with duplicate keys
    (even when contradictory keys are present).
    """
    loader.flatten_mapping(node)
    mapping = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        try:
            duplicate = key in mapping
        except TypeError as exc:
            raise ConstructorError(
                'while constructing a mapping',
                node.start_mark,
                'found an unhashable key',
                key_node.start_mark,
            ) from exc

        if duplicate:
            raise ConstructorError(
                'while constructing a mapping',
                node.start_mark,
                'found duplicate key %r' % key,
                key_node.start_mark,
            )

        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


_UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    _construct_unique_mapping,
)


def _load_config(config):
    """ Loads a YAML recipe into a dictionary
    """
    if not isinstance(config, (str, os.PathLike)):
        raise TypeError('config must be a YAML recipe path')

    path = Path(config).expanduser()
    try:
        with path.open('r', encoding='utf-8') as handle:
            loaded = yaml.load(handle, Loader=_UniqueKeyLoader)
    except OSError as exc:
        raise WorkflowConfigError(
            'could not read configuration %s: %s' % (path, exc)
        ) from exc
    except UnicodeError as exc:
        raise WorkflowConfigError(
            'could not decode configuration %s: %s' % (path, exc)
        ) from exc
    except yaml.YAMLError as exc:
        raise WorkflowConfigError(
            'invalid YAML in %s: %s' % (path, exc)
        ) from exc

    if loaded is None:
        raise WorkflowConfigError('configuration is empty')
    if not isinstance(loaded, dict):
        raise WorkflowConfigError(
            'top-level YAML value must be a mapping (dictionary)'
        )
    return loaded


def validate_config(config):
    """ Validates and normalizes an MTUQ YAML recipe

    .. rubric :: Input arguments

    ``config`` (`str` or `os.PathLike`)
        Path to an abridged or complete YAML recipe. Relative input paths are
        interpreted from the recipe directory.

    .. rubric :: Returns

    A normalized configuration dictionary suitable for construction of MTUQ
    objects. Includes normalized scientific inputs and absolute input paths.
    Values determined from constructed MTUQ objects are excluded.

    Relative output paths are interpreted from the current working directory.
    """
    if not isinstance(config, (str, os.PathLike)):
        raise TypeError('config must be a YAML recipe path')

    recipe_path = Path(config).expanduser()
    recipe_dir = recipe_path.resolve().parent
    config = _load_config(recipe_path)

    unknown = set(config) - _TOP_LEVEL_KEYS
    if unknown:
        formatted = ', '.join(
            str(key) if isinstance(key, str) else repr(key)
            for key in sorted(unknown, key=repr)
        )
        raise WorkflowConfigError(
            'unknown top-level key(s): %s' % formatted
        )

    version = config.get('version')
    if type(version) is not int or version != WORKFLOW_VERSION:
        raise WorkflowConfigError(
            'version must be integer %d' % WORKFLOW_VERSION
        )

    _validate_event(config.get('event'))

    origin_search = copy.deepcopy(config.get('origin_search'))
    if origin_search is not None:
        _validate_origin_search(origin_search)

    data = _normalize_data(config.get('data'), recipe_dir=recipe_dir)
    greens = _normalize_greens(config.get('greens'), recipe_dir=recipe_dir)

    picks = config.get('picks')
    if picks is not None:
        _validate_picks(picks)

    misfit = copy.deepcopy(config.get('misfit'))
    _validate_misfit(misfit)

    measurements = _validate_measurements(
        config.get('measurements'),
        data=data,
        greens=greens,
        picks=picks,
        recipe_dir=recipe_dir,
    )

    objective = None
    if 'objective' in config:
        objective = _validate_objective(
            config['objective'], list(measurements)
        )

    plots = None
    if 'plots' in config:
        plots = _validate_plots(config['plots'])

    source = copy.deepcopy(config.get('source'))
    source = _require_mapping(source, 'source')
    grid_cfg = _require_mapping(source.get('grid'), 'source.grid')
    grid_cfg.pop('function', None)
    grid_cfg.pop('size', None)
    _validate_source(source)

    wavelet = copy.deepcopy(config.get('wavelet', {'type': 'trapezoid'}))
    wavelet = _require_mapping(wavelet, 'wavelet')
    wavelet.pop('function', None)
    _validate_wavelet(wavelet)

    _validate_generated_metadata(config.get('workflow'), config.get('mtuq'))

    output = config.get('output')
    if output is None:
        output = os.path.join('output', str(config['event']['id']))
    elif not isinstance(output, str):
        raise WorkflowConfigError('output must be a path string')
    # Input paths belong to the recipe; output belongs to the invocation.
    output = _resolve_path(output, Path.cwd())

    normalized = copy.deepcopy(config)
    normalized['data'] = data
    if origin_search is not None:
        normalized['origin_search'] = origin_search
    normalized['greens'] = greens
    normalized['misfit'] = misfit
    normalized['measurements'] = measurements
    if objective is not None:
        normalized['objective'] = objective
    if plots is not None:
        normalized['plots'] = plots
    normalized['source'] = source
    normalized['wavelet'] = wavelet
    normalized['output'] = output
    normalized.pop('picks', None)
    normalized.pop('workflow', None)
    normalized.pop('mtuq', None)

    return normalized


def _normalize_data(data, recipe_dir):
    data = copy.deepcopy(_require_mapping(data, 'data'))
    allowed = {'format', 'path', 'weights', 'units', 'tags'}
    _reject_unknown(data, allowed, 'data')
    _require_keys(data, {'format', 'path', 'weights'}, 'data')

    for key in ('format', 'path', 'weights'):
        if not isinstance(data[key], str) or not data[key].strip():
            raise WorkflowConfigError(
                'data.%s must be a non-empty string' % key
            )

    if 'tags' in data:
        if not isinstance(data['tags'], list) or not data['tags'] or not all(
            isinstance(tag, str) for tag in data['tags']
        ):
            raise WorkflowConfigError(
                'data.tags must be a non-empty list of strings'
            )

    if 'units' in data:
        if not isinstance(data['units'], str):
            raise WorkflowConfigError('data.units must be a string')

        units = data['units'].lower()
        if units not in _UNIT_TAGS:
            raise WorkflowConfigError(
                'unsupported data.units %r; choose one of %s'
                % (data['units'], ', '.join(sorted(_UNIT_TAGS)))
            )

        expected_tags = list(_UNIT_TAGS[units])
        if 'tags' in data and data['tags'] != expected_tags:
            raise WorkflowConfigError(
                'conflicting values for data.units and data.tags'
            )
        data['tags'] = expected_tags
        data.pop('units')

    if 'tags' not in data:
        raise WorkflowConfigError('data requires either units or tags')

    data['path'] = _resolve_path(data['path'], recipe_dir)
    data['weights'] = _resolve_path(data['weights'], recipe_dir)
    if not Path(data['weights']).is_file():
        raise WorkflowConfigError(
            'data.weights does not exist: %s' % data['weights']
        )

    return data


def _normalize_greens(greens, recipe_dir):
    greens = copy.deepcopy(_require_mapping(greens, 'greens'))
    allowed = {'format', 'path', 'model', 'cache_path'}
    _reject_unknown(greens, allowed, 'greens')
    _require_keys(greens, {'format'}, 'greens')

    if not isinstance(greens['format'], str) or not greens['format'].strip():
        raise WorkflowConfigError('greens.format must be a non-empty string')

    for key in ('path', 'model', 'cache_path'):
        if key in greens and greens[key] is not None and not isinstance(
            greens[key], str
        ):
            raise WorkflowConfigError('greens.%s must be a string' % key)

    fmt = greens['format'].upper()
    if fmt == 'SYNGINE':
        if (
            not isinstance(greens.get('model'), str)
            or not greens['model'].strip()
        ):
            raise WorkflowConfigError('greens.model is required for SYNGINE')
        if 'path' in greens:
            raise WorkflowConfigError(
                'greens.path is not supported for SYNGINE'
            )
    elif (
        not isinstance(greens.get('path'), str)
        or not greens['path'].strip()
    ):
        raise WorkflowConfigError(
            'greens.path is required for non-SYNGINE formats'
        )

    for key in ('path', 'cache_path'):
        if greens.get(key) is not None:
            greens[key] = _resolve_path(greens[key], recipe_dir)

    return greens


def _validate_generated_metadata(workflow, mtuq):
    if workflow is not None:
        workflow = _require_mapping(workflow, 'workflow')
        _reject_unknown(workflow, {'version'}, 'workflow')

    if mtuq is not None:
        mtuq = _require_mapping(mtuq, 'mtuq')
        _reject_unknown(mtuq, {'version', 'git_commit'}, 'mtuq')


def _require_mapping(value, name):
    if not isinstance(value, Mapping):
        raise WorkflowConfigError('%s must be a mapping' % name)
    return value


def _reject_unknown(mapping, allowed, name):
    unknown = set(mapping) - set(allowed)
    if unknown:
        formatted = ', '.join(
            str(key) if isinstance(key, str) else repr(key)
            for key in sorted(unknown, key=repr)
        )
        raise WorkflowConfigError(
            '%s has unknown key(s): %s' % (name, formatted)
        )


def _require_keys(mapping, required, name):
    missing = [key for key in required if key not in mapping]
    if missing:
        raise WorkflowConfigError(
            '%s is missing required key(s): %s'
            % (name, ', '.join(missing))
        )


def _decimal_literal(text, name):
    if not _NUMERIC_LITERAL_RE.fullmatch(text):
        raise WorkflowConfigError(
            '%s must be a finite number or simple fraction' % name
        )
    try:
        value = Decimal(text.replace('_', ''))
    except InvalidOperation as exc:
        raise WorkflowConfigError(
            '%s must be a finite number or simple fraction' % name
        ) from exc
    if not value.is_finite():
        raise WorkflowConfigError('%s must be a finite number' % name)
    return value


def _decimal_number(value, name):
    if isinstance(value, (bool, np.bool_)):
        raise WorkflowConfigError('%s must be a finite number' % name)

    if isinstance(value, (int, np.integer)):
        return Decimal(int(value))

    if isinstance(value, (float, np.floating)):
        number = float(value)
        if not math.isfinite(number):
            raise WorkflowConfigError('%s must be a finite number' % name)
        return Decimal(str(number))

    if not isinstance(value, str):
        raise WorkflowConfigError('%s must be a finite number' % name)

    text = value.strip()
    if not text:
        raise WorkflowConfigError('%s must be a finite number' % name)

    if '/' not in text:
        return _decimal_literal(text, name)

    if text.count('/') != 1:
        raise WorkflowConfigError(
            '%s must be a finite number or simple fraction' % name
        )

    numerator_text, denominator_text = (
        part.strip() for part in text.split('/')
    )
    numerator = _decimal_literal(numerator_text, name)
    denominator = _decimal_literal(denominator_text, name)
    if denominator == 0:
        raise WorkflowConfigError('%s may not divide by zero' % name)
    return numerator / denominator


def _coerce_number(value, name):
    """ Returns a finite float from a number or simple fraction
    """
    decimal = _decimal_number(value, name)
    number = float(decimal)
    if not math.isfinite(number):
        raise WorkflowConfigError('%s must be a finite number' % name)
    return number


def _is_finite_number(value):
    try:
        _coerce_number(value, 'value')
    except WorkflowConfigError:
        return False
    return True


def _validate_event(event):
    event = _require_mapping(event, 'event')
    allowed = {'id', 'time', 'latitude', 'longitude', 'depth_in_m'}
    _reject_unknown(event, allowed, 'event')
    _require_keys(event, allowed, 'event')

    if isinstance(event['id'], (bool, np.bool_)) or not isinstance(
        event['id'], (str, int)
    ):
        raise WorkflowConfigError('event.id must be a string or integer')
    event['id'] = str(event['id'])
    if not _EVENT_ID_RE.fullmatch(event['id']):
        raise WorkflowConfigError(
            'event.id must start with a letter or number and contain only '
            "letters, numbers, '.', '_', or '-'"
        )

    event_time = event['time']
    if isinstance(event_time, str):
        if not event_time.strip():
            raise WorkflowConfigError('event.time must be non-empty')
    elif not isinstance(event_time, datetime):
        raise WorkflowConfigError(
            'event.time must be a timestamp string or datetime'
        )

    for key in ('latitude', 'longitude', 'depth_in_m'):
        event[key] = _coerce_number(event[key], 'event.%s' % key)


def _validate_origin_search(origin_search):
    # note: I have not (yet) enforced constraints on duplicate depth values
    origin_search = _require_mapping(origin_search, 'origin_search')
    _reject_unknown(
        origin_search, {'depth_in_m', 'hypocenter'}, 'origin_search'
    )
    if not origin_search:
        raise WorkflowConfigError(
            'origin_search requires depth_in_m or hypocenter'
        )

    if 'depth_in_m' in origin_search:
        depth = _require_mapping(
            origin_search['depth_in_m'], 'origin_search.depth_in_m'
        )
        _reject_unknown(depth, {'values'}, 'origin_search.depth_in_m')
        _require_keys(depth, {'values'}, 'origin_search.depth_in_m')

        values = depth['values']
        if not isinstance(values, (list, tuple)) or not values:
            raise WorkflowConfigError(
                'origin_search.depth_in_m.values must be a non-empty list'
            )
        depth['values'] = [
            _coerce_number(
                value, 'origin_search.depth_in_m.values[%d]' % index
            )
            for index, value in enumerate(values)
        ]

    if 'hypocenter' in origin_search:
        hypocenter = _require_mapping(
            origin_search['hypocenter'], 'origin_search.hypocenter'
        )
        keys = {'spacing_in_m', 'npts_per_edge'}
        _reject_unknown(hypocenter, keys, 'origin_search.hypocenter')
        _require_keys(hypocenter, keys, 'origin_search.hypocenter')

        spacing = _coerce_number(
            hypocenter['spacing_in_m'],
            'origin_search.hypocenter.spacing_in_m',
        )
        if spacing <= 0:
            raise WorkflowConfigError(
                'origin_search.hypocenter.spacing_in_m must be positive'
            )
        hypocenter['spacing_in_m'] = spacing
        hypocenter['npts_per_edge'] = _validate_positive_integer(
            hypocenter['npts_per_edge'],
            'origin_search.hypocenter.npts_per_edge',
        )


def _validate_picks(picks):
    picks = _require_mapping(picks, 'picks')
    allowed = {'type', 'model'}
    _reject_unknown(picks, allowed, 'picks')
    _require_keys(picks, {'type'}, 'picks')

    if (
        not isinstance(picks['type'], str)
        or picks['type'] not in _SUPPORTED_PICK_TYPES
    ):
        raise WorkflowConfigError(
            'unsupported picks.type %r' % picks['type']
        )

    if picks['type'] == 'taup':
        if 'model' not in picks or not isinstance(picks['model'], str):
            raise WorkflowConfigError('picks.model is required for taup')


def _validate_misfit(misfit):
    misfit = _require_mapping(misfit, 'misfit')
    allowed = {'norm', 'normalize', 'level', 'verbose'}
    _reject_unknown(misfit, allowed, 'misfit')
    _require_keys(misfit, {'norm', 'normalize'}, 'misfit')

    # Check these here because WaveformMisfit can give unclear errors for bad
    # configuration values. Check bool separately because Python treats it as
    # an integer.
    if not isinstance(misfit['norm'], str) or misfit['norm'] not in {
        'L1',
        'L2',
        'hybrid',
    }:
        raise WorkflowConfigError('misfit.norm must be L1, L2, or hybrid')

    if not isinstance(misfit['normalize'], bool):
        raise WorkflowConfigError('misfit.normalize must be boolean')

    defaults = _signature_defaults(WaveformMisfit.__init__)
    misfit.setdefault('level', defaults['level'])
    misfit.setdefault('verbose', defaults['verbose'])

    level = misfit['level']
    if (
        isinstance(level, (bool, np.bool_))
        or not isinstance(level, (int, float, np.integer, np.floating))
        or level not in {0, 1, 2}
    ):
        raise WorkflowConfigError('misfit.level must be 0, 1, or 2')
    misfit['level'] = int(level)

    if isinstance(misfit['verbose'], bool) or not isinstance(
        misfit['verbose'], (int, np.integer)
    ):
        raise WorkflowConfigError('misfit.verbose must be an integer')
    misfit['verbose'] = int(misfit['verbose'])


def _validate_measurements(measurements, data, greens, picks, recipe_dir):
    """Validates and normalizes waveform measurement terms.

    Each entry under ``measurements`` defines one waveform-misfit term.

    The optional ``role`` identifies how a measurement should be used by
    waveform plotting, for example as a body, surface, Rayleigh, or Love term.
    The standard measurement names ``body``, ``surface``, ``rayleigh``, and
    ``love`` imply the corresponding role automatically. Custom measurement
    names may specify a role explicitly.

    Only waveform measurements are currently supported. First-motion polarity
    measurements are not yet supported by the workflow.
    """
    measurements = _require_mapping(measurements, 'measurements')
    if not measurements:
        raise WorkflowConfigError(
            'measurements must contain at least one term'
        )

    normalized = {}
    role_names = {}
    for name, measurement in measurements.items():
        if (
            not isinstance(name, str)
            or re.fullmatch('[A-Za-z0-9][A-Za-z0-9_-]*', name) is None
        ):
            raise WorkflowConfigError(
                "measurement names may contain letters, numbers, '-' and '_'"
            )
        if name == 'total':
            raise WorkflowConfigError(
                "measurement name 'total' is reserved for combined results"
            )

        path = 'measurements.%s' % name
        measurement = copy.deepcopy(_require_mapping(measurement, path))
        allowed = {
            'filter',
            'period',
            'window',
            'components',
            'time_shift',
            'role',
            'processing',
            'waveform_misfit',
        }
        _reject_unknown(measurement, allowed, path)

        inferred_role = name if name in _SUPPORTED_MEASUREMENT_ROLES else None
        role = measurement.get('role', inferred_role)
        if 'role' in measurement:
            if (
                not isinstance(role, str)
                or role not in _SUPPORTED_MEASUREMENT_ROLES
            ):
                raise WorkflowConfigError(
                    '%s.role must be body, surface, rayleigh, or love' % path
                )
            if inferred_role is not None and role != inferred_role:
                raise WorkflowConfigError(
                    '%s.role must match the standard measurement name %r'
                    % (path, inferred_role)
                )
        if role is not None:
            if role in role_names:
                raise WorkflowConfigError(
                    "measurement role %r is already used by %s"
                    % (role, role_names[role])
                )
            role_names[role] = path

        processing = _normalize_processing(
            name,
            measurement,
            data=data,
            greens=greens,
            picks=picks,
            recipe_dir=recipe_dir,
        )
        waveform_misfit = _normalize_waveform_misfit(
            name,
            measurement,
        )
        normalized_measurement = {
            'processing': processing,
            'waveform_misfit': waveform_misfit,
        }
        if role is not None:
            normalized_measurement['role'] = role
        normalized[name] = normalized_measurement

    return normalized


def _normalize_processing(
    name, measurement, data, greens, picks, recipe_dir
):
    path = 'measurements.%s' % name
    shorthand = {}

    if 'filter' in measurement and 'period' in measurement:
        raise WorkflowConfigError(
            '%s may specify filter or period, but not both' % path
        )

    if 'filter' in measurement:
        shorthand.update(_validate_filter(measurement['filter'], path))

    if 'period' in measurement:
        period_min, period_max = _validate_period(measurement['period'], path)
        shorthand.update(
            filter_type='Bandpass',
            period_min=period_min,
            period_max=period_max,
        )

    if 'window' in measurement:
        window_type, window_length = _validate_window(
            measurement['window'], path
        )
        shorthand.update(
            window_type=window_type,
            window_length=window_length,
        )

    if picks is not None:
        shorthand['pick_type'] = picks['type']
        if picks['type'] == 'taup':
            shorthand['taup_model'] = picks['model']
        elif picks['type'] == 'FK_metadata':
            if greens.get('path') is not None:
                shorthand['FK_database'] = greens['path']
            if picks.get('model') is not None:
                shorthand['FK_model'] = picks['model']
            elif greens.get('model') is not None:
                shorthand['FK_model'] = greens['model']

    shorthand['capuaf_file'] = data['weights']

    explicit = measurement.get('processing', {})
    explicit = copy.deepcopy(_require_mapping(explicit, path + '.processing'))
    allowed = {
        'filter_type',
        'freq',
        'freq_min',
        'freq_max',
        'period',
        'period_min',
        'period_max',
        'pick_type',
        'taup_model',
        'FK_database',
        'FK_model',
        'window_type',
        'window_length',
        'apply_padding',
        'apply_statics',
        'time_shift_min',
        'time_shift_max',
        'apply_weights',
        'apply_scaling',
        'scaling_power',
        'scaling_coefficient',
        'capuaf_file',
    }
    _reject_unknown(explicit, allowed, path + '.processing')

    for key in ('FK_database', 'capuaf_file'):
        if explicit.get(key) is not None:
            if not isinstance(explicit[key], (str, os.PathLike)):
                raise WorkflowConfigError(
                    '%s.processing.%s must be a path string' % (path, key)
                )
            explicit[key] = _resolve_path(explicit[key], recipe_dir)

    processing = _merge_effective(
        shorthand,
        explicit,
        path + '.processing',
    )

    for key in (
        'freq',
        'freq_min',
        'freq_max',
        'period',
        'period_min',
        'period_max',
        'window_length',
        'time_shift_min',
        'time_shift_max',
        'scaling_power',
        'scaling_coefficient',
    ):
        if processing.get(key) is not None:
            processing[key] = _coerce_number(
                processing[key], '%s.processing.%s' % (path, key)
            )

    # If padding is explicitly enabled in an abridged recipe, the shorthand
    # time-shift interval is the natural padding interval unless the user
    # supplies matching explicit processing bounds.
    if processing.get('apply_padding') and 'time_shift' in measurement:
        shift_min, shift_max = _resolve_time_shift(measurement['time_shift'])
        processing = _merge_effective(
            {
                'time_shift_min': shift_min,
                'time_shift_max': shift_max,
            },
            processing,
            path + '.processing',
        )

    if (
        processing.get('pick_type') == 'FK_metadata'
        and processing.get('FK_database') is None
    ):
        raise WorkflowConfigError(
            '%s.processing requires FK_database for FK_metadata picks' % path
        )

    _validate_processing(processing, path + '.processing')
    return processing


def _normalize_waveform_misfit(name, measurement):
    path = 'measurements.%s' % name
    shorthand = {}

    if 'components' in measurement:
        shorthand['time_shift_groups'] = _validate_component_groups(
            measurement['components'], path + '.components'
        )

    if 'time_shift' in measurement:
        shift_min, shift_max = _resolve_time_shift(measurement['time_shift'])
        shorthand['time_shift_min'] = shift_min
        shorthand['time_shift_max'] = shift_max

    explicit = measurement.get('waveform_misfit', {})
    explicit = copy.deepcopy(
        _require_mapping(explicit, path + '.waveform_misfit')
    )
    allowed = {
        'time_shift_min',
        'time_shift_max',
        'time_shift_groups',
    }
    _reject_unknown(explicit, allowed, path + '.waveform_misfit')

    waveform = _merge_effective(
        shorthand,
        explicit,
        path + '.waveform_misfit',
    )

    if 'time_shift_groups' not in waveform:
        raise WorkflowConfigError(
            '%s requires components or waveform_misfit.time_shift_groups'
            % path
        )
    if 'time_shift_min' not in waveform or 'time_shift_max' not in waveform:
        raise WorkflowConfigError(
            '%s requires time_shift or explicit time_shift_min/time_shift_max'
            % path
        )

    waveform['time_shift_groups'] = _validate_component_groups(
        waveform['time_shift_groups'],
        path + '.waveform_misfit.time_shift_groups',
    )
    minimum, maximum = _validate_shift_bounds(
        waveform['time_shift_min'],
        waveform['time_shift_max'],
        path + '.waveform_misfit',
    )
    waveform['time_shift_min'] = minimum
    waveform['time_shift_max'] = maximum
    return waveform


def _validate_filter(value, path):
    if isinstance(value, (list, tuple)):
        if len(value) != 2:
            raise WorkflowConfigError(
                '%s.filter must be [freq_min, freq_max] or a '
                'lowpass/highpass mapping' % path
            )

        freq_min = _coerce_number(value[0], path + '.filter[0]')
        freq_max = _coerce_number(value[1], path + '.filter[1]')
        if not (0.0 < freq_min < freq_max):
            raise WorkflowConfigError(
                'measurement filter must satisfy 0 < freq_min < freq_max'
            )
        return {
            'filter_type': 'Bandpass',
            'freq_min': freq_min,
            'freq_max': freq_max,
        }

    filter_config = copy.deepcopy(
        _require_mapping(value, path + '.filter')
    )
    _reject_unknown(
        filter_config,
        {'type', 'frequency', 'period'},
        path + '.filter',
    )
    _require_keys(filter_config, {'type'}, path + '.filter')

    filter_type = filter_config['type']
    if (
        not isinstance(filter_type, str)
        or filter_type.lower() not in {'lowpass', 'highpass'}
    ):
        raise WorkflowConfigError(
            '%s.filter.type must be lowpass or highpass' % path
        )
    filter_type = filter_type.lower()

    supplied = [
        key for key in ('frequency', 'period') if key in filter_config
    ]
    if len(supplied) != 1:
        raise WorkflowConfigError(
            '%s.filter requires exactly one of frequency or period' % path
        )

    input_key = supplied[0]
    value = _coerce_number(
        filter_config[input_key],
        '%s.filter.%s' % (path, input_key),
    )
    if value <= 0.0:
        raise WorkflowConfigError(
            '%s.filter.%s must be positive' % (path, input_key)
        )

    native_key = 'freq' if input_key == 'frequency' else 'period'
    return {
        'filter_type': filter_type.title(),
        native_key: value,
    }


def _validate_period(value, path):
    if not isinstance(value, (list, tuple)) or len(value) != 2:
        raise WorkflowConfigError(
            '%s.period must be [period_min, period_max]' % path
        )

    period_min = _coerce_number(value[0], path + '.period[0]')
    period_max = _coerce_number(value[1], path + '.period[1]')
    if not (0.0 < period_min < period_max):
        raise WorkflowConfigError(
            'measurement period must satisfy 0 < period_min < period_max'
        )
    return period_min, period_max


def _validate_window(value, path):
    if not isinstance(value, (list, tuple)) or len(value) != 2:
        raise WorkflowConfigError(
            '%s.window must be [window_type, length]' % path
        )
    window_type = value[0]
    if window_type not in _SUPPORTED_WINDOW_TYPES:
        raise WorkflowConfigError(
            'unsupported window type %r in measurement %s'
            % (window_type, path.split('.')[-1])
        )
    window_length = _coerce_number(value[1], path + '.window[1]')
    if window_length <= 0.0:
        raise WorkflowConfigError('measurement window length must be positive')
    return window_type, window_length


def _validate_component_groups(groups, path):
    if not isinstance(groups, (list, tuple)) or not groups:
        raise WorkflowConfigError('%s must be a non-empty list' % path)

    normalized = []
    used_components = set()
    for group in groups:
        if not isinstance(group, str) or not group:
            raise WorkflowConfigError(
                'component groups must be non-empty strings'
            )
        if any(component not in 'ZRT' for component in group):
            raise WorkflowConfigError(
                'component groups may contain only Z, R, and T'
            )
        if len(set(group)) != len(group):
            raise WorkflowConfigError(
                'component groups may not repeat components'
            )
        overlap = used_components.intersection(group)
        if overlap:
            raise WorkflowConfigError(
                'component groups may not overlap within one measurement'
            )
        used_components.update(group)
        normalized.append(group)
    return normalized


def _validate_processing(processing, path):
    """ Checks processing options supported by the YAML interface

    Remaining checks are left to ``ProcessData`` construction.
    """
    _require_keys(
        processing,
        {
            'filter_type', 'pick_type', 'window_type', 'window_length',
            'capuaf_file',
        },
        path,
    )

    filter_type = processing['filter_type']
    if not isinstance(filter_type, str) or filter_type.lower() not in {
        'bandpass', 'lowpass', 'highpass'
    }:
        raise WorkflowConfigError(
            '%s.filter_type must be Bandpass, Lowpass, or Highpass' % path
        )
    filter_type = filter_type.lower()
    processing['filter_type'] = filter_type.title()

    band_frequency = {'freq_min', 'freq_max'}.intersection(processing)
    band_period = {'period_min', 'period_max'}.intersection(processing)
    single_frequency = 'freq' in processing
    single_period = 'period' in processing

    if filter_type == 'bandpass':
        if single_frequency or single_period:
            raise WorkflowConfigError(
                '%s Bandpass requires frequency or period corner pairs' % path
            )
        if band_frequency and band_period:
            raise WorkflowConfigError(
                '%s may specify frequency corners or period corners, '
                'but not both' % path
            )
        if band_frequency:
            _require_keys(processing, {'freq_min', 'freq_max'}, path)
        elif band_period:
            _require_keys(processing, {'period_min', 'period_max'}, path)
        else:
            raise WorkflowConfigError(
                '%s requires freq_min/freq_max or period_min/period_max'
                % path
            )
    else:
        if band_frequency or band_period:
            raise WorkflowConfigError(
                '%s %s requires one frequency or period cutoff'
                % (path, processing['filter_type'])
            )
        if single_frequency == single_period:
            raise WorkflowConfigError(
                '%s %s requires exactly one of freq or period'
                % (path, processing['filter_type'])
            )
        cutoff_key = 'freq' if single_frequency else 'period'
        if processing[cutoff_key] <= 0.0:
            raise WorkflowConfigError(
                '%s.%s must be positive' % (path, cutoff_key)
            )

    if (
        not isinstance(processing['window_type'], str)
        or processing['window_type'] not in _SUPPORTED_WINDOW_TYPES
    ):
        raise WorkflowConfigError(
            'unsupported window_type %r' % processing['window_type']
        )

    if (
        not isinstance(processing['pick_type'], str)
        or processing['pick_type'] not in _SUPPORTED_PICK_TYPES
    ):
        raise WorkflowConfigError(
            'unsupported pick_type %r' % processing['pick_type']
        )

    for key in (
        'apply_padding',
        'apply_statics',
        'apply_weights',
        'apply_scaling',
    ):
        if key in processing and not isinstance(processing[key], bool):
            raise WorkflowConfigError('%s.%s must be boolean' % (path, key))


def _validate_shift_bounds(minimum, maximum, path):
    minimum = _coerce_number(minimum, path + '.time_shift_min')
    maximum = _coerce_number(maximum, path + '.time_shift_max')
    if minimum > 0.0 or maximum < 0.0 or minimum > maximum:
        raise WorkflowConfigError(
            '%s must satisfy time_shift_min <= 0 <= time_shift_max' % path
        )
    return minimum, maximum


def _merge_effective(shorthand, explicit, path):
    merged = copy.deepcopy(shorthand)
    for key, value in explicit.items():
        if key in merged and not _effective_values_equal(
            key, merged[key], value
        ):
            raise WorkflowConfigError(
                'conflicting values for %s.%s: shorthand resolves to %r '
                'but explicit value is %r'
                % (path, key, merged[key], value)
            )
        merged[key] = copy.deepcopy(value)
    return merged


def _effective_values_equal(key, first, second):
    if key in {'filter_type', 'window_type'}:
        return str(first).lower() == str(second).lower()
    if key in _NUMERIC_OVERRIDE_KEYS:
        if not _is_finite_number(first) or not _is_finite_number(second):
            return False
        return _coerce_number(first, 'value') == _coerce_number(
            second, 'value'
        )
    if isinstance(first, (list, tuple)) and isinstance(second, (list, tuple)):
        return list(first) == list(second)
    if isinstance(first, os.PathLike):
        first = os.fspath(first)
    if isinstance(second, os.PathLike):
        second = os.fspath(second)
    return first == second


def _validate_source(source):
    source = _require_mapping(source, 'source')
    allowed = {'type', 'magnitudes', 'grid'}
    _reject_unknown(source, allowed, 'source')
    _require_keys(source, allowed, 'source')

    source_type = source['type']
    if (
        not isinstance(source_type, str)
        or source_type not in {'dc', 'dev', 'fmt'}
    ):
        raise WorkflowConfigError('source.type must be dc, dev, or fmt')

    magnitudes = source['magnitudes']
    if not isinstance(magnitudes, (list, tuple)) or not magnitudes:
        raise WorkflowConfigError('source.magnitudes must be a non-empty list')
    source['magnitudes'] = [
        _coerce_number(value, 'source.magnitudes[%d]' % index)
        for index, value in enumerate(magnitudes)
    ]

    grid = _require_mapping(source['grid'], 'source.grid')
    _reject_unknown(
        grid,
        {'type', 'npts', 'npts_per_axis', 'tightness', 'uniformity'},
        'source.grid',
    )
    _require_keys(grid, {'type'}, 'source.grid')

    grid_type = grid['type']
    if not isinstance(grid_type, str):
        raise WorkflowConfigError(
            'source.grid.type must be regular or random'
        )
    if grid_type == 'regular':
        if 'npts' in grid:
            raise WorkflowConfigError(
                'source.grid.npts is only valid for random grids'
            )
        _require_keys(grid, {'npts_per_axis'}, 'source.grid')
        grid['npts_per_axis'] = _validate_positive_integer(
            grid['npts_per_axis'], 'source.grid.npts_per_axis'
        )

        if source_type in {'dev', 'fmt'}:
            defaults = _signature_defaults(
                _SOURCE_FUNCTIONS[(source_type, grid_type)]
            )
            grid.setdefault('tightness', defaults['tightness'])
            grid.setdefault('uniformity', defaults['uniformity'])
            grid['tightness'] = _coerce_number(
                grid['tightness'], 'source.grid.tightness'
            )
            grid['uniformity'] = _coerce_number(
                grid['uniformity'], 'source.grid.uniformity'
            )
        elif 'tightness' in grid or 'uniformity' in grid:
            raise WorkflowConfigError(
                'source.grid.tightness/uniformity apply only to DEV/FMT '
                'regular grids'
            )
    elif grid_type == 'random':
        if 'npts_per_axis' in grid:
            raise WorkflowConfigError(
                'source.grid.npts_per_axis is only valid for regular grids'
            )
        if 'tightness' in grid or 'uniformity' in grid:
            raise WorkflowConfigError(
                'source.grid.tightness/uniformity apply only to DEV/FMT '
                'regular grids'
            )
        _require_keys(grid, {'npts'}, 'source.grid')
        grid['npts'] = _validate_positive_integer(
            grid['npts'], 'source.grid.npts'
        )
    else:
        raise WorkflowConfigError('source.grid.type must be regular or random')

    if (source_type, grid_type) not in _SOURCE_FUNCTIONS:
        raise WorkflowConfigError(
            'unsupported source/grid combination: %s/%s'
            % (source_type, grid_type)
        )


def _validate_wavelet(wavelet):
    wavelet = _require_mapping(wavelet, 'wavelet')
    _require_keys(wavelet, {'type'}, 'wavelet')

    wavelet_type = wavelet['type']
    if not isinstance(wavelet_type, str):
        raise WorkflowConfigError('wavelet.type must be a string')

    parameters = {
        'trapezoid': {'magnitude', 'rise_time', 'half_duration'},
        'triangle': {'half_duration'},
        'gaussian': {'sigma', 'mu'},
        'gabor': {'a', 'b'},
        'earthquake_trapezoid': {'rise_time', 'rupture_time'},
        'ricker': {'dominant_frequency'},
        'gabor_wavelet': {'dominant_frequency'},
    }
    if wavelet_type not in parameters:
        raise WorkflowConfigError(
            'wavelet.type must be trapezoid, triangle, gaussian, gabor, '
            'earthquake_trapezoid, ricker, or gabor_wavelet'
        )

    _reject_unknown(
        wavelet,
        {'type'} | parameters[wavelet_type],
        'wavelet',
    )

    for key in parameters[wavelet_type]:
        if key in wavelet:
            wavelet[key] = _coerce_number(
                wavelet[key], 'wavelet.%s' % key
            )

    if wavelet_type == 'trapezoid':
        has_shape = 'rise_time' in wavelet or 'half_duration' in wavelet
        if has_shape:
            if 'magnitude' in wavelet:
                raise WorkflowConfigError(
                    'wavelet.trapezoid may use magnitude or '
                    'rise_time/half_duration, but not both'
                )
            _require_keys(
                wavelet,
                {'rise_time', 'half_duration'},
                'wavelet',
            )
            if wavelet['rise_time'] <= 0.0:
                raise WorkflowConfigError(
                    'wavelet.rise_time must be positive'
                )
            if wavelet['half_duration'] <= 0.0:
                raise WorkflowConfigError(
                    'wavelet.half_duration must be positive'
                )
            if wavelet['rise_time'] > wavelet['half_duration']:
                raise WorkflowConfigError(
                    'wavelet.rise_time must not exceed half_duration'
                )
        return

    if wavelet_type == 'triangle':
        _require_keys(wavelet, {'half_duration'}, 'wavelet')
        if wavelet['half_duration'] <= 0.0:
            raise WorkflowConfigError(
                'wavelet.half_duration must be positive'
            )
        return

    if wavelet_type == 'gaussian':
        if 'sigma' in wavelet and wavelet['sigma'] <= 0.0:
            raise WorkflowConfigError('wavelet.sigma must be positive')
        return

    if wavelet_type == 'gabor':
        return

    if wavelet_type == 'earthquake_trapezoid':
        _require_keys(
            wavelet,
            {'rise_time', 'rupture_time'},
            'wavelet',
        )
        if wavelet['rise_time'] <= 0.0:
            raise WorkflowConfigError('wavelet.rise_time must be positive')
        if wavelet['rupture_time'] <= 0.0:
            raise WorkflowConfigError('wavelet.rupture_time must be positive')
        if wavelet['rupture_time'] < wavelet['rise_time']:
            raise WorkflowConfigError(
                'wavelet.rupture_time must be at least rise_time'
            )
        return

    _require_keys(wavelet, {'dominant_frequency'}, 'wavelet')
    if wavelet['dominant_frequency'] <= 0.0:
        raise WorkflowConfigError(
            'wavelet.dominant_frequency must be positive'
        )


def _validate_positive_integer(value, name):
    number = _decimal_number(value, name)
    if number <= 0 or number != number.to_integral_value():
        raise WorkflowConfigError('%s must be a positive integer' % name)
    return int(number)


def _validate_objective(objective, names):
    objective = copy.deepcopy(_require_mapping(objective, 'objective'))
    _reject_unknown(objective, {'coefficients'}, 'objective')
    _require_keys(objective, {'coefficients'}, 'objective')

    coefficients = _require_mapping(
        objective['coefficients'], 'objective.coefficients'
    )
    _reject_unknown(coefficients, names, 'objective.coefficients')
    _require_keys(coefficients, names, 'objective.coefficients')

    normalized = {}
    for name in names:
        path = 'objective.coefficients.%s' % name
        value = _coerce_number(coefficients[name], path)
        if value < 0.0:
            raise WorkflowConfigError('%s must be non-negative' % path)
        normalized[name] = value

    if not any(value > 0.0 for value in normalized.values()):
        raise WorkflowConfigError(
            'objective.coefficients must contain at least one positive value'
        )

    return {'coefficients': normalized}


def _validate_plots(plots):
    if not isinstance(plots, (list, tuple)) or not plots:
        raise WorkflowConfigError('plots must be a non-empty list')

    normalized = []
    for name in plots:
        if not isinstance(name, str) or name not in _SUPPORTED_PLOTS:
            raise WorkflowConfigError(
                'unsupported plot %r; choose waveform, beachball, or misfit'
                % name
            )
        if name in normalized:
            raise WorkflowConfigError('plots may not contain duplicates')
        normalized.append(name)
    return normalized


def _resolve_time_shift(value):
    if not isinstance(value, (list, tuple)):
        number = _coerce_number(value, 'time_shift')
        if number < 0.0:
            raise WorkflowConfigError('scalar time_shift must be non-negative')
        return -number, number

    if len(value) == 2:
        minimum = _coerce_number(value[0], 'time_shift[0]')
        maximum = _coerce_number(value[1], 'time_shift[1]')
        if minimum > 0.0 or maximum < 0.0 or minimum > maximum:
            raise WorkflowConfigError(
                'time_shift interval must satisfy min <= 0 <= max'
            )
        return minimum, maximum

    raise WorkflowConfigError(
        'time_shift must be a non-negative scalar or [min, max]'
    )


def _signature_defaults(callable_):
    defaults = {}
    signature = inspect.signature(callable_)
    for name, parameter in signature.parameters.items():
        if name == 'self' or parameter.kind in {
            inspect.Parameter.VAR_POSITIONAL,
            inspect.Parameter.VAR_KEYWORD,
        }:
            continue
        if parameter.default is not inspect.Parameter.empty:
            defaults[name] = parameter.default
    return defaults
